"""empty message

Revision ID: 0e4f9bbc0c44
Revises: 1be57b6eeb7b
Create Date: 2020-11-15 01:00:50.310941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e4f9bbc0c44'
down_revision = '1be57b6eeb7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('b64data', sa.Text(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_cat_id'), 'thumbnail', ['cat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_cat_id'), table_name='thumbnail')
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
