"""update tables

Revision ID: 1be57b6eeb7b
Revises: 64d15a8113a5
Create Date: 2020-09-25 17:56:47.966599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be57b6eeb7b'
down_revision = '64d15a8113a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cat', sa.Column('index', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_cat_index'), 'cat', ['index'], unique=False)
    op.add_column('visitor', sa.Column('last_cat_idx', sa.Integer(), nullable=True))
    op.add_column('visitor', sa.Column('t_last_seen', sa.DateTime(), nullable=True))
    op.drop_column('visitor', 't_seen')
    op.drop_column('visitor', 'last_cat_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('last_cat_id', sa.INTEGER(), nullable=True))
    op.add_column('visitor', sa.Column('t_seen', sa.DATETIME(), nullable=True))
    op.drop_column('visitor', 't_last_seen')
    op.drop_column('visitor', 'last_cat_idx')
    op.drop_index(op.f('ix_cat_index'), table_name='cat')
    op.drop_column('cat', 'index')
    # ### end Alembic commands ###
