"""empty message

Revision ID: 26afe48bf8c7
Revises: decc161197f6
Create Date: 2020-11-25 23:05:49.673967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26afe48bf8c7'
down_revision = 'decc161197f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=32), nullable=True),
    sa.Column('remote_addr', sa.String(length=16), nullable=True),
    sa.Column('t_last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_cat_idx', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_etag'), 'visitor', ['etag'], unique=False)
    op.create_index(op.f('ix_visitor_remote_addr'), 'visitor', ['remote_addr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_remote_addr'), table_name='visitor')
    op.drop_index(op.f('ix_visitor_etag'), table_name='visitor')
    op.drop_table('visitor')
    # ### end Alembic commands ###
