"""empty message

Revision ID: 2787922761ba
Revises: 26afe48bf8c7
Create Date: 2020-12-11 02:02:27.006938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2787922761ba'
down_revision = '26afe48bf8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thumbnail_cat_id', table_name='thumbnail')
    op.drop_table('thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cat_id', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_thumbnail_cat_id', 'thumbnail', ['cat_id'], unique=1)
    # ### end Alembic commands ###
