"""empty message

Revision ID: 36a516f6dcac
Revises: cb4c5149f71c
Create Date: 2020-11-15 01:14:50.827992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36a516f6dcac'
down_revision = 'cb4c5149f71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_cat_id'), 'thumbnail', ['cat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_cat_id'), table_name='thumbnail')
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
