"""empty message

Revision ID: 6745bbd818c4
Revises: 4665e6b437e4
Create Date: 2020-11-15 01:12:26.287857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6745bbd818c4'
down_revision = '4665e6b437e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thumbnail', 'b64data')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thumbnail', sa.Column('b64data', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
