"""visitors table

Revision ID: 81e2dad2ce8e
Revises: 
Create Date: 2020-09-25 16:56:42.331663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81e2dad2ce8e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=32), nullable=True),
    sa.Column('t_seen', sa.DateTime(), nullable=True),
    sa.Column('last_cat_id', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_etag'), 'visitor', ['etag'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_etag'), table_name='visitor')
    op.drop_table('visitor')
    # ### end Alembic commands ###
