"""empty message

Revision ID: 82418382ed41
Revises: 
Create Date: 2020-12-11 17:23:06.513416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82418382ed41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=320), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cat_index'), 'cat', ['index'], unique=False)
    op.create_table('thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_cat_id'), 'thumbnail', ['cat_id'], unique=True)
    op.create_table('visitor',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('etag', sa.String(length=32), nullable=True),
    sa.Column('remote_addr', sa.String(length=16), nullable=True),
    sa.Column('t_last_seen', sa.DateTime(), nullable=True),
    sa.Column('last_cat_idx', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visitor_etag'), 'visitor', ['etag'], unique=False)
    op.create_index(op.f('ix_visitor_remote_addr'), 'visitor', ['remote_addr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_remote_addr'), table_name='visitor')
    op.drop_index(op.f('ix_visitor_etag'), table_name='visitor')
    op.drop_table('visitor')
    op.drop_index(op.f('ix_thumbnail_cat_id'), table_name='thumbnail')
    op.drop_table('thumbnail')
    op.drop_index(op.f('ix_cat_index'), table_name='cat')
    op.drop_table('cat')
    # ### end Alembic commands ###
