"""empty message

Revision ID: 8b155fe06ab2
Revises: 2787922761ba
Create Date: 2020-12-11 02:03:03.450954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b155fe06ab2'
down_revision = '2787922761ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cat_id', sa.Integer(), nullable=True),
    sa.Column('data', sa.LargeBinary(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_cat_id'), 'thumbnail', ['cat_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_cat_id'), table_name='thumbnail')
    op.drop_table('thumbnail')
    # ### end Alembic commands ###
