"""empty message

Revision ID: cb4c5149f71c
Revises: 6745bbd818c4
Create Date: 2020-11-15 01:14:23.806808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb4c5149f71c'
down_revision = '6745bbd818c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_thumbnail_cat_id', table_name='thumbnail')
    op.drop_table('thumbnail')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('cat_id', sa.INTEGER(), nullable=True),
    sa.Column('b64data', sa.TEXT(), nullable=True),
    sa.Column('width', sa.INTEGER(), nullable=True),
    sa.Column('data', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_thumbnail_cat_id', 'thumbnail', ['cat_id'], unique=1)
    # ### end Alembic commands ###
