"""add remote address of visitor

Revision ID: d28cc7b0ccf4
Revises: 36a516f6dcac
Create Date: 2020-11-25 22:30:43.306575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28cc7b0ccf4'
down_revision = '36a516f6dcac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('remote_addr', sa.String(length=16), nullable=True))
    op.create_index(op.f('ix_visitor_remote_addr'), 'visitor', ['remote_addr'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_visitor_remote_addr'), table_name='visitor')
    op.drop_column('visitor', 'remote_addr')
    # ### end Alembic commands ###
