"""empty message

Revision ID: de583f8e2035
Revises: f7a2d904a648
Create Date: 2020-11-25 23:04:53.274312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de583f8e2035'
down_revision = 'f7a2d904a648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visitor', 'deleted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visitor', sa.Column('deleted', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
