"""drop visitors table

Revision ID: decc161197f6
Revises: de583f8e2035
Create Date: 2020-11-25 23:05:28.422207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'decc161197f6'
down_revision = 'de583f8e2035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_visitor_etag', table_name='visitor')
    op.drop_index('ix_visitor_remote_addr', table_name='visitor')
    op.drop_table('visitor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('visitor',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('etag', sa.VARCHAR(length=32), nullable=True),
    sa.Column('last_cat_idx', sa.INTEGER(), nullable=True),
    sa.Column('t_last_seen', sa.DATETIME(), nullable=True),
    sa.Column('deleted', sa.BOOLEAN(), nullable=True),
    sa.Column('remote_addr', sa.VARCHAR(length=16), nullable=True),
    sa.CheckConstraint('deleted IN (0,1)'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_visitor_remote_addr', 'visitor', ['remote_addr'], unique=False)
    op.create_index('ix_visitor_etag', 'visitor', ['etag'], unique=False)
    # ### end Alembic commands ###
